version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:latest'
    environment:  
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: main
    ports: 
      - '3306'

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ### 
